[project]
name = "packpub-tuto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[all]>=0.122.0",
    "scalar-fastapi>=1.4.4",
]
